### ISSUE TITLE
The file ui_rigid_body_simulator.h appears to be missing. 

### ISSUE THREAD

**Issue by bsenftner** [diegomacario/Dyna-Kinematics#2]
The file  ui_rigid_body_simulator.h is not in the repository, at the time I'm writing this...

**Comment by diegomacario** [comment]
Hi Blake! That file is actually generated by the Qt User Interface Compiler when it reads this UI file: rigid_body_simulator.ui

It's something that's done automatically when you build the project.

I'll leave more details in the other issue you opened, just to centralize the information there.

**Comment by diegomacario** [comment]
Build instructions are now available [here](https://github.com/diegomacario/Dyna-Kinematics/blob/master/BUILD_INSTRUCTIONS.md).

Thank you!
